### PR TITLE
etcd: try put again when ch had closed

### PR DESCRIPTION
**Pull request by veloting**

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

can you provide more information about the problem that solve your PR?

**Comment by veloting** [comment]
@ldez etcd lease will expire when there is a problem with the network or etcd server that more than keepalive ttl. 
the ch will close when keepalive had a problem, maybe it's better to try to put until the network or etcd server is ok

**Comment by veloting** [comment]
1.put(key, value, opt.keepalive=true) to etcd 
2. kill etcd server 
3. wait for 30s 
4. start etcd server

problem:
5. the key will not exist in the etcd server

expect:
5 the (key, value) will put again in etcd server

**Comment by veloting** [comment]
@ldez should i provide more information?

**Comment by ldez** [comment]
I think it's not the right solution to implement a naive retry.
The topic needs to be dug more.
Hello,

We changed the core system of Valkeyrie: now the stores have dedicated repositories.

The new repository for etcdv3: https://github.com/kvtools/etcdv3

I recommend creating an issue about the topic in this repository.

**Comment by veloting** [comment]
@ldez

**Comment by veloting** [comment]
@ldez 
thank you for your reply
but if the keepalive channel is closed the key will expired later
the put caller need run a new more goroutine to check the key is expired

**Pull request closed without merging**
